export const GET_MY_STORIES_REQUEST = 'GET_MY_STORIES_REQUEST';
export const GET_MY_STORIES_SUCCESS = 'GET_MY_STORIES_SUCCESS';
export const GET_MY_STORIES_FAILURE = 'GET_MY_STORIES_FAILURE';
export const INVALIDATE_GET_MY_STORIES = 'INVALIDATE_GET_MY_STORIES';
export const SET_FILTER_TYPE = 'MY_STORIES/SET_FILTER_TYPE';