import React from 'react';

const Story2 = () => {

  return (<div className="background_dbdddd vh91">

    <div className="container storyWrapper">
      <div className="row noMargin">
        <div className="storyBannerImg banner_story_2 layout horizontal vertical center-center">
          <div className="storyBannerImgTint">
            <p className="color_FFF storyBannerText text-center noMargin">Happily, thereafter.</p>
          </div>
        </div>

        <div className="margin24 noSideMargin fontSize_5">
          <p className="">Once upon a time in a faraway place, far away from anything, there lived a man and a woman. His name was Johann and hers was Elise. Johann had white skin and Elise’s was brown. This didn’t matter in the beginning, but over time, it would, first in small ways, tiny little cracks, and then in ways they could no longer ignore. Johann first saw Elise in a smoke-filled room, and decided he wanted her, wanted to know the taste of her brown skin, wanted to run his hands over the soft curves of her ample body. Elise didn’t believe him. She didn’t believe in fairy tales or herself or much of anything. Johann chased her and chased her and finally, she let him take her to dinner because she was hungry. Elise let him have a drink at her house because she was lonely. She let him touch her because she was another kind of hungry. She lay with him and enjoyed the meat of his body against hers, how his rough hands held her sweetly, how his lips brushed her shoulder. Johann brought her pleasure and she brought him pleasure and after, he lay next to her, breathing heavy. Elise thanked him. She told him to leave. He did so but vowed to return, ignoring her protests. </p>
          <p className="">Johann sent Elise a beautiful bouquet of fragrant wildflowers. She called and said thank you and please don’t do that again but she set the flowers on the coffee table in her living room and smiled at them each day. He continued to call and sometimes she answered and they talked about all manner of things. Johann persisted in his pursuit and Elise finally relented and accompanied him to more dinners and sometimes, they had drinks and sometimes they saw moving pictures and she always let him spend the night. Soon, Elise had forgotten there ever was a time when she didn’t want Johann around.</p>
          <p className="">The man was so different. Elise often worried he was too different. Johann worked with his hands and had never been beyond the borders of the far away place far from anything. He knew things about the stars and the position of the sun. He knew about secret waterfalls in the heart of the deep woods and he showed them to her, let her drink that cool clean water from his rough, calloused hands. Elise worked with her mind and sometimes her heart. She knew about words and spent her days studying books. She spoke different languages and had traveled to lands across oceans and further even still. She longed to be closer to places where she could find bright lights and crowded streets and where once in a while she might see someone who looked like her. But Elise had a job to do and studies to complete. She would bide her time. Johann and Elise knew little of the same things but he knew how to touch her and how to press his lips to her neck and how to hold her as she slept and if all that mattered was the moments shared between them, they could have easily found a happily ever after.</p>
          <p className="">There were, however, other things that mattered. Johann had a wicked mother who lived in a grand house high on a hill. She kept an extravagant garden and enjoyed receiving visitors in a large living room filled with large, imposing furniture. The wicked mother scowled more than she smiled. The wicked mother thought her son a king and wanted nothing but the best for her oldest boy. She did not think Elise was any kind of good enough and she let that be known throughout the land. Elise brought Johann’s wicked mother gifts and kind words. She said please and thank you and when invited to dinner, she offered to wash the dishes. None of her gestures could sway the wicked mother who did not want Johann to love a woman with such different skin. It was a scandal, she said. Think of the family name, she said. Soon, Elise stopped going to the grand house high on the hill. She and Johann pretended the wicked mother didn’t matter. Her displeasure was an unfortunate detail, they told themselves. They ignored the harsh words and the harsh thoughts. They pretended nothing could get in the way of their happy and ever after. On festive days though, when there was much to celebrate, Elise often found herself alone and waiting while Johann paid his respects and feted with his family. In those lonely moments, Elise wanted Johann to make a choice but she didn’t dare ask, couldn’t bear knowing he might not choose her.</p>
          <p className="">There came a day when Elise learned she was carrying Johann’s child. It was an unexpected but welcome blessing. When she told the Johann, he said his heart was so full it ached. He offered his hand in marriage and a place in his kingdom, at his side. Elise told him they would wait and see. She wanted to say yes. They began planning for a future and when they saw the doctor and heard the beating heart of their unborn child, they looked at each other and discovered they did share one thing—love. Johann and Elise were so blinded by their joy, they shared their good news with Johann’s wicked mother who, upon hearing the news of a new heir in the kingdom, a bastard heir, she said, she narrowed her eyes into hard, black slits. She said no such child, a child from two terribly different worlds, would ever be recognized or loved by anyone under her reign. Elise held her hands against her stomach, tried to shield her beloved unborn child from such venomous words. The wicked mother banished Elise from her home and Johann stood by and said nothing, torn between his mother and would be wife. Elise hoped to find a way to forgive his silence. She would never forget.</p>
          <p className="">It happened on an ordinary day full of extraordinary moments, a day when Johann painted the nursery a soft shade of pink for the child who would be a girl who would be named Emma. He stood in the room admiring his work, picturing his woman holding their child near the large window, perhaps staring up at the sky. Elise stood in the kitchen preparing her man a fine meal, humming to her baby, trusting in her joy. She was overcome by a sudden, terrible pain in the seat of her womb. It was a pain so sharp and precise, she couldn’t make a single sound. The last moment Elise remembered was falling to her knees and thinking, “I cannot bear to lose this.”Johann found her, on the floor, bleeding slowly, breathing shallow after their home filled with the smell of burning meat. They both mourned the loss of the child but instead of tearing them apart, their sorrow made them love each other better and more fiercely.</p>
          <p className="">When she finished her studies, Elise told Johann she had to leave the far away place, far away from anything. She had been offered a position for which she had prepared her entire life. It was too hard to live amongst so many memories of what should have been. She didn’t want to raise children in a place where its citizens would always look upon them as more hers than his. Johann said he understood. He said they would find a way to love each other across an impossible distance. She believed him. She trusted in her joy. </p>
          <p className="">On the eve of her departure, Johann sat next to Elise on a wooden pier. They looked out on moonlit waters, their heads dizzy with wine. He said the most beautiful things she had ever heard a man say to a woman. He presented her with a ring, a beautiful diamond in the shape of a tear. He tried to slide the ring on her finger but it did not fit. Elise laughed, nervously, said it was a bad omen. Johann said they would fix the ring. He said it was just a detail, and details didn’t matter. He said, please, take this ring, please stay here, with me, in my kingdom. Elise looked at the beautiful ring and thought of how she had never shared how much she loved him. She thought about how he made her forget all the tragedies that had befallen her before he loved her. She tried to stop herself but she cried and felt her heart falling apart. </p>
          <p className="">Johann thought her tears meant she was saying yes. Elise handed Johann his ring, her hands shaking. She said, I can’t stay; I cannot believe you asked. She said you do not know me at all; the details do matter. She said you should have asked if you could leave this place with me. Johann said he had never known any other kind of life. He said these were his people and this was his land. He said he would spend his life making her love that land the way he did, that his family would grow to accept her. He grew angry, said she was his, said he would never let her go. Elise held her stomach, remembered the child once growing there and how the loss of her bound them together so tightly. They sat together in silence, the night air cooling everything between them. She understood she had been right about fairy tales all along.</p>
        </div>
      </div>

    </div>
  </div>);
};

export default Story2;