export const VIEW_STORY_REQUEST = 'VIEW_STORY_REQUEST';
export const VIEW_STORY_SUCCESS = 'VIEW_STORY_SUCCESS';
export const VIEW_STORY_FAILURE = 'VIEW_STORY_FAILURE';
export const INVALIDATE_VIEW_STORY = 'INVALIDATE_VIEW_STORY';
