export const ADD_STORY_REQUEST = 'ADD_STORY_REQUEST';
export const ADD_STORY_SUCCESS = 'ADD_STORY_SUCCESS';
export const ADD_STORY_FAILURE = 'ADD_STORY_FAILURE';
export const INVALIDATE_ADD_STORY = 'INVALIDATE_ADD_STORY';
