export const GET_STORIES_REQUEST = 'GET_STORIES_REQUEST';
export const GET_STORIES_SUCCESS = 'GET_STORIES_SUCCESS';
export const GET_STORIES_FAILURE = 'GET_STORIES_FAILURE';
export const INVALIDATE_GET_STORIES = 'INVALIDATE_GET_STORIES';
export const SET_FILTER_TYPE = 'SET_FILTER_TYPE';