export const LOGIN_USER_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_FAILURE';
export const INVALIDATE_LOGIN_USER = 'INVALIDATE_LOGIN';

